### ISSUE TITLE
--veloapp-updated hook is skipped when migrating from old Squirrel

### ISSUE THREAD

**Issue by Noah1989** [velopack/velopack#402] opened 2024-12-13 00:35 UTC
### OS

Windows 11 (22H2 Build 22621.4460)

### Programming Language

.NET Framework 4.8

### VPK Version

Velopack CLI 0.0.942

### Library Version

NuGet v0.0.942

### What happened?

When updating an installation that is currently using old Squirrel, both the `--veloapp-obsolete` and `--veloapp-updated` hooks are skipped. I understand the first one to be skipped (because the old version does not know it) but skipping `--veloapp-updated` leaves no opportunity to run necessary custom steps ensuring the application works well with the new version.

**Comment by caesay** [comment] 2024-12-13 11:09
I understand this might be an inconvenience but it's currently by design. Lots of things are changing during the migrations and I felt the hooks added unnecessary complexity.

**Comment by Noah1989** [comment] 2024-12-14 16:51
Hm.. I have to do the cleanup on the first application startup then. Not ideal, but doable.

**Comment by caesay** [comment] 2024-12-14 18:18
I don't know if there'd be any obvious way to detect the migration just happened using velopack, you'd have to roll something custom.

I think I'd be able to add support for the updated hook, I guess you'd run into the same problem though.. The updated hook always runs, so doesn't necessarily inform that the migration has just happened.

**Comment by Noah1989** [comment] 2024-12-19 13:50
Hm.. that is true. I mis-remembered that the update hook passed both old and new version as a parameter, but that does not seem to be the case.

I guess enabling the hooks on migration could be done alongside https://github.com/velopack/velopack/issues/303
Due to the time limit I am currently moving custom logic out of the hooks anyway until that feature is implemented.

Thanks!

**Comment by caesay** [comment] 2024-12-19 15:03
Given this thread is now linked from #303 I'm going to close this, who knows what the hooks will look like after that change :)

**Closed by caesay** 2024-12-19 15:03 UTC
