### ISSUE TITLE
Improve wording around Setup Repair dialog

### ISSUE THREAD

**Issue by stefanolson** [velopack/velopack#3] opened 2024-01-07 21:39 UTC
Continuing my testing. I don't have a Web server set up for my test so I just copied the setup EXE across. 1.0.1 is installed, but this is a newer version, 1.0.2, but it brings up a screen that says it is already installed suggesting that I repair the application install.  If it is a later version could it please just automatically install the application?  

I often have scenarios where I get people to reinstall the whole setup if it's failing to update to newer or I need to force a major update

**Comment by stefanolson** [comment] 2024-01-07 21:40
When I tried repair I get this, application not running at the time:
![image](https://github.com/velopack/velopack/assets/1751192/eab3ed9f-de41-4ab0-8137-53b6fe57f996)

**Comment by stefanolson** [comment] 2024-01-07 21:42
I think that may have been because I had the folder open in Windows Explorer

**Comment by caesay** [comment] 2024-01-08 07:57
Hi there, the new setup logic is:

If the setup folder exists and is not empty, you'll get the "cancel/repair" dialog. If you hit repair, it will try and remove the old folder by closing any processes running inside it, renaming it, installing the new version, and then deleting the old folder. If there are any issues with the installation, it will roll back to the previous installation. If it can't rename the folder (eg. files are locked by a cmd.exe window or explorer) then it will fail.

**Comment by stefanolson** [comment] 2024-01-08 08:02
That's going to be very confusing to our customers who don't have that kind of concept of repairing something when we are specifically asking them to install a new version - will end up with a lot of support calls.  Our customers are not very computer literate in that the idea of repairing rather than installing is going to cause a lot of confusion.  I'll check with management but I don't think I'll be allowed to use this if it displays that message for a new version upgrade. I'll try see if I can go back to your 3.0 version.  I think I may be able to use this for one of our applications that is internal but not anything that external customers are going to see sadly.

**Comment by caesay** [comment] 2024-01-08 08:14
There is a fundamental difference between what the installer does and what an updater does. The installer wipes out and replaces the application directory entirely, while updates just replace the application files. This does often result in users running a new installer and accidentally deleting settings files and so forth. 

If you would like to suggest some improved wording for that dialog - if you think the current "Repair?" is confusing, I would consider changing that?

**Comment by Trinitek** [comment] 2024-01-10 12:01
+1 on this. I really need the Setup.exe to "just work" without any prompts. My customers are not going to know what to do if they get a dialog box. I am completely serious.

If this is something that can be addressed, and if there's a concern about wiping out config files living in the install directory (which my app does not do), I am thinking you could add some switch set at packaging time when building the setup.exe that says, yes, you can proceed with the repair without asking. Or there could be a metadata file in the installation directory that says "yes I do write to the install folder," and the repair process can act accordingly.

**Comment by caesay** [comment] 2024-01-16 21:45
I have changed the dialog behavior to the following: 

If the application is installed, but is an older version than what is currently being installed:
![image](https://github.com/velopack/velopack/assets/1287295/66b4e762-a366-4465-990b-6125104f5d85)

If the application is installed, but is a newer version than what is currently being installed:
![image](https://github.com/velopack/velopack/assets/1287295/111324b3-e6b9-4668-85e5-a211c7e0d759)

If the application is the same version, or the version can not be determined:
![image](https://github.com/velopack/velopack/assets/1287295/a86e078f-26cc-4edb-a5a6-dd29770e8dee)

I'm closing this issue for now, however if either of you feel unsatisfied with this solution please let me know and I'll consider re-opening!

**Comment by stefanolson** [comment] 2024-01-16 22:02
That looks great. Will test that. Thanks!

**Comment by Trinitek** [comment] 2024-05-07 09:04
I've changed my mind on the dialog and I think it's a good thing to have. In my previous comment I was still in the mindset that I would have to regularly ask my customers to re-run the Setup.exe to repair their installs, as was the case with Squirrel.Windows.

However I would like to ask if we can be provided an option to change the subtext of the action buttons. "Backup or save your work first" does not make sense for my application because it persists user data after repair and uninstall by design. Likewise I would like to modify the Repair subtext to additionally read "Your work will not be deleted."

**Comment by madorjan** [comment] 2024-07-05 07:44
Tested this with version 0.0.556. It works when updating from velopack-install to velopack-install. Squirrel install overwrites always show the default repair dialog:

[setup:23136] [09:38:26] [INFO] Reading bundle header...
[setup:23136] [09:38:26] [INFO] Bundle offset = 2531328, length = 128567120
[setup:23136] [09:38:26] [INFO] Loading bundle from embedded zip...
[setup:23136] [09:38:26] [INFO] Bundle loaded successfully.
[setup:23136] [09:38:26] [INFO] Reading package manifest...
[setup:23136] [09:38:26] [INFO] Package manifest loaded successfully.
[setup:23136] [09:38:26] [INFO]     Package ID: ProductName
[setup:23136] [09:38:26] [INFO]     Package Version: 24.3.1
[setup:23136] [09:38:26] [INFO]     Package Title: CompanyName ProductName
[setup:23136] [09:38:26] [INFO]     Package Authors: CompanyName
[setup:23136] [09:38:26] [INFO]     Package Description: CompanyName ProductName
[setup:23136] [09:38:26] [INFO]     Package Machine Architecture: 
[setup:23136] [09:38:26] [INFO]     Package Runtime Dependencies: 
[setup:23136] [09:38:26] [INFO] Attempting to open global system mutex: 'velopack-ProductName'
[setup:23136] [09:38:26] [INFO] Checking application pre-requisites...
[setup:23136] [09:38:26] [INFO] Determining install directory...
[setup:23136] [09:38:26] [INFO] Installation Directory: "C:\\Users\\User\\AppData\\Local\\ProductName"
[setup:23136] [09:38:26] [INFO] There is 676.27 Gbit free space available at destination, this package requires 495.04 Mbit.
[setup:23136] [09:38:26] [WARN] Unable to find current manifest, checking for latest full package. (LEGACY MODE)
[setup:23136] [09:38:26] [DEBUG] (1) velopack::shared::util_windows: Scanning for packages in "C:\\Users\\User\\AppData\\Local\\ProductName\\packages"
[setup:23136] [09:38:26] [DEBUG] (1) velopack::shared::util_windows: Found package: C:\Users\User\AppData\Local\ProductName\packages\ProductName-23.4.1-full.nupkg
[setup:23136] [09:38:26] [DEBUG] (1) velopack::shared::bundle: Loading bundle from file 'C:\Users\User\AppData\Local\ProductName\packages\ProductName-23.4.1-full.nupkg'...

**Comment by caesay** [comment] 2024-09-26 23:16
I'm going to be working on #60 and #68 soon, and I'm going to try and see if we can allow developer-provided translation overrides. In which case you can customise the dialog text to your heart's content. Therefore I am closing this issue

**Closed by caesay** 2024-09-26 23:16 UTC
Labels: enhancement
