### ISSUE TITLE
Update fails if `current` directory was ever accessed

### ISSUE THREAD

**Issue by genment** [velopack/velopack#240] opened 2024-09-23 22:51 UTC
### OS

Windows 10 19045.4894

### Programming Language

dotnet 8, c#

### VPK Version

0.0.594

### Library Version

0.0.594

## Issue

`Update.exe` checks the `current` directory to see if it is locked using `filelocksmith` ([code reference](https://github.com/velopack/velopack/blob/6f1a94e3d4b823b5a83338643845be5769a123b6/src/bins/src/windows/locksmith.rs#L7)).

This makes sense if any process is locking or accessing the `current` directory or any file within it. However, the `explorer.exe` is so sepecial - it holds handles for every directory a user has accessed previously, until the user closes that specific **explorer window** (you can verify this behavior using [this method](https://superuser.com/a/643312)).

While users typically don't access the `current` directory, if they do, it causes `Update.exe` to fail during the update process. Personally, I often have many explorer windows open and navigate around directories, making it difficult to track which explorer window previously accessed the `current` directory. This results in me either having to close all explorer windows or cancel the update.

Interestingly, deleting directories or files that have handles held by `explorer.exe` **appears** to be safe, even when the user is accessing them. It simply navigates the user to the parent directory. For example, if I have `D:\a\b\c` open in explorer and delete `D:\a` from the terminal, it just navigates to `D:\` automatically.

## Suggestion

Could `explorer.exe` be whitelisted from lock checks?

## Screenshot
![Image](https://github.com/user-attachments/assets/a8560420-312c-4b1d-959f-f8af511edb7a)

### Relevant log output

```shell
[update:27136] [17:02:13] [ERROR] Error applying package: Failed to close processes locking directory / user cancelled.
[update:27136] [17:02:13] [INFO] About to launch: 'R:\App\current\App.exe' in dir 'R:\App\current'
[update:27136] [17:02:13] [INFO] Args: CommandArgs { inner: [] }
[update:27136] [17:02:13] [ERROR] Apply error: Apply failed, see logs for details.
```

**Comment by caesay** [comment] 2024-11-07 20:58
I can't reproduce this on Windows 11, given it's a rare case I'm going to close this as not-planned for now. If Windows Explorer is open inside the `current` directory, I can see that it blocks updates (as expected), but as soon as I navigate away from that folder (eg. by clicking the ^ up button) the update can proceed.

**Closed by caesay** 2024-11-07 20:58 UTC
Labels: bug
